In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

import pandas as pd # cannot use external libraries, just pandas for data exploration

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [3]:
print(tX.shape)
print(y.shape)

(250000, 30)
(250000,)


## Data exploration

In [4]:
DATA_TEST_PATH = '../data/test.csv'
train = pd.read_csv(DATA_TRAIN_PATH)
test = pd.read_csv(DATA_TEST_PATH)
train.head()

Id Prediction  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  \
0  100000          s       138.470                       51.655        97.827   
1  100001          b       160.937                       68.768       103.235   
2  100002          b      -999.000                      162.172       125.953   
3  100003          b       143.905                       81.417        80.943   
4  100004          b       175.864                       16.915       134.805   

   DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0    27.980                  0.91           124.711                2.666   
1    48.146               -999.00          -999.000             -999.000   
2    35.635               -999.00          -999.000             -999.000   
3     0.414               -999.00          -999.000             -999.000   
4    16.405               -999.00          -999.000             -999.000   

   DER_deltar_tau_lep       ...        PRI_met_phi  PRI_met_sumet  \
0               3.064       ...             -0.277        258.733   
1               3.473       ...             -1.916        164.546   
2               3.148       ...             -2.186        260.414   
3               3.310       ...              0.060         86.062   
4               3.891       ...             -0.871         53.131   

   PRI_jet_num  PRI_jet_leading_pt  PRI_jet_leading_eta  PRI_jet_leading_phi  \
0            2              67.435                2.150                0.444   
1            1              46.226                0.725                1.158   
2            1              44.251                2.053               -2.028   
3            0            -999.000             -999.000             -999.000   
4            0            -999.000             -999.000             -999.000   

   PRI_jet_subleading_pt  PRI_jet_subleading_eta  PRI_jet_subleading_phi  \
0                 46.062                    1.24                  -2.475   
1               -999.000                 -999.00                -999.000   
2               -999.000                 -999.00                -999.000   
3               -999.000                 -999.00                -999.000   
4               -999.000                 -999.00                -999.000   

   PRI_jet_all_pt  
0         113.497  
1          46.226  
2          44.251  
3           0.000  
4           0.000  

[5 rows x 32 columns]

In [5]:
print('Train set size: {} samples x {} features'.format(pd.DataFrame(tX).shape[0], pd.DataFrame(tX).shape[1]))
print('Test set size: {} samples x {} features'.format(test.shape[0], pd.DataFrame(tX).shape[1]))

Train set size: 250000 samples x 30 features
Test set size: 568238 samples x 30 features


In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 32 columns):
Id                             250000 non-null int64
Prediction                     250000 non-null object
DER_mass_MMC                   250000 non-null float64
DER_mass_transverse_met_lep    250000 non-null float64
DER_mass_vis                   250000 non-null float64
DER_pt_h                       250000 non-null float64
DER_deltaeta_jet_jet           250000 non-null float64
DER_mass_jet_jet               250000 non-null float64
DER_prodeta_jet_jet            250000 non-null float64
DER_deltar_tau_lep             250000 non-null float64
DER_pt_tot                     250000 non-null float64
DER_sum_pt                     250000 non-null float64
DER_pt_ratio_lep_tau           250000 non-null float64
DER_met_phi_centrality         250000 non-null float64
DER_lep_eta_centrality         250000 non-null float64
PRI_tau_pt                     250000 non-null float64
PRI_tau_eta 

Looks clean!

In [7]:
train.describe()

Id   DER_mass_MMC  DER_mass_transverse_met_lep  \
count  250000.000000  250000.000000                250000.000000   
mean   224999.500000     -49.023079                    49.239819   
std     72168.927986     406.345647                    35.344886   
min    100000.000000    -999.000000                     0.000000   
25%    162499.750000      78.100750                    19.241000   
50%    224999.500000     105.012000                    46.524000   
75%    287499.250000     130.606250                    73.598000   
max    349999.000000    1192.026000                   690.075000   

        DER_mass_vis       DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  \
count  250000.000000  250000.000000         250000.000000     250000.000000   
mean       81.181982      57.895962           -708.420675       -601.237051   
std        40.828691      63.655682            454.480565        657.972302   
min         6.329000       0.000000           -999.000000       -999.000000   
25%        59.388750      14.068750           -999.000000       -999.000000   
50%        73.752000      38.467500           -999.000000       -999.000000   
75%        92.259000      79.169000              0.490000         83.446000   
max      1349.351000    2834.999000              8.503000       4974.979000   

       DER_prodeta_jet_jet  DER_deltar_tau_lep     DER_pt_tot       ...        \
count        250000.000000       250000.000000  250000.000000       ...         
mean           -709.356603            2.373100      18.917332       ...         
std             453.019877            0.782911      22.273494       ...         
min            -999.000000            0.208000       0.000000       ...         
25%            -999.000000            1.810000       2.841000       ...         
50%            -999.000000            2.491500      12.315500       ...         
75%              -4.593000            2.961000      27.591000       ...         
max              16.690000            5.684000    2834.999000       ...         

         PRI_met_phi  PRI_met_sumet    PRI_jet_num  PRI_jet_leading_pt  \
count  250000.000000  250000.000000  250000.000000       250000.000000   
mean       -0.010119     209.797178       0.979176         -348.329567   
std         1.812223     126.499506       0.977426          532.962789   
min        -3.142000      13.678000       0.000000         -999.000000   
25%        -1.575000     123.017500       0.000000         -999.000000   
50%        -0.024000     179.739000       1.000000           38.960000   
75%         1.561000     263.379250       2.000000           75.349000   
max         3.142000    2003.976000       3.000000         1120.573000   

       PRI_jet_leading_eta  PRI_jet_leading_phi  PRI_jet_subleading_pt  \
count        250000.000000        250000.000000          250000.000000   
mean           -399.254314          -399.259788            -692.381204   
std             489.338286           489.333883             479.875496   
min            -999.000000          -999.000000            -999.000000   
25%            -999.000000          -999.000000            -999.000000   
50%              -1.872000            -2.093000            -999.000000   
75%               0.433000             0.503000              33.703000   
max               4.499000             3.141000             721.456000   

       PRI_jet_subleading_eta  PRI_jet_subleading_phi  PRI_jet_all_pt  
count           250000.000000           250000.000000   250000.000000  
mean              -709.121609             -709.118631       73.064591  
std                453.384624              453.389017       98.015662  
min               -999.000000             -999.000000        0.000000  
25%               -999.000000             -999.000000        0.000000  
50%               -999.000000             -999.000000       40.512500  
75%                 -2.457000               -2.275000      109.933750  
max                  4.500000                3.142000

In [ ]:
#train.hist(bins=50, figsize=(20,15))

## ML methods

#### Helpers

In [8]:
# As we'redealing with large arrays, we will use the batch iter method in order to avoid memory access problems
def batch_iter(y, tx, batch_size, num_batches=1, shuffle=True):
    """
    Generate a minibatch iterator for a dataset.
    Takes as input two iterables (here the output desired values 'y' and the input data 'tx')
    Outputs an iterator which gives mini-batches of `batch_size` matching elements from `y` and `tx`.
    Data can be randomly shuffled to avoid ordering in the original data messing with the randomness of the minibatches.
    Example of use :
    for minibatch_y, minibatch_tx in batch_iter(y, tx, 32):
    """
    data_size = len(y)

    if shuffle:
        shuffle_indices = np.random.permutation(np.arange(data_size))
        shuffled_y = y[shuffle_indices]
        shuffled_tx = tx[shuffle_indices]
    else:
        shuffled_y = y
        shuffled_tx = tx
    for batch_num in range(num_batches):
        start_index = batch_num * batch_size
        end_index = min((batch_num + 1) * batch_size, data_size)
        if start_index != end_index:
            yield shuffled_y[start_index:end_index], shuffled_tx[start_index:end_index]

#### Least squares

In [9]:
def compute_mse(y, tx, w):
    '''Compute MSE loss.'''
    e = y - tx.dot(w)
    mse = (1/2) * np.mean(e**2)
    return mse

def calculate_mse(e):
    """Calculate the mse for vector e."""
    return 1/2*np.mean(e**2)


def calculate_mae(e):
    """Calculate the mae for vector e."""
    return np.mean(np.abs(e))


def compute_loss_ls(y, tx, w):
    """
    Calculate the least-square loss using mse.
    """
    e = y - tx.dot(w)
    return calculate_mse(e)

In [10]:
def compute_gradient_ls(y, tx, w):
    """Compute the gradient."""
    err = y - tx.dot(w)
    grad = -tx.T.dot(err) / len(err)
    return grad

In [11]:
def least_squares_GD(y, tx, initial_w, max_iters, gamma):
    """Linear regression using gradient descent."""
    w = initial_w
    
    for i in range(max_iters):
        # gradient
        gradient = compute_gradient_ls(y, tx, w)
        
        # loss
        loss = compute_loss_ls(y, tx, w)
        
        # update rule
        w -= gamma * gradient
        
    return w, loss

In [12]:
def least_squares_GD(y, tx, initial_w, maxiters, gamma):
    """Linear regression using gradient descent (GD)."""
    eps = 10E-5
    assert(y.shape[0] == tx.shape[0])
    w = initial_w
    maxreached = False
    N = len(y)
    for i in range(0, maxiters+1):
        loss = np.linalg.norm(tx @ w - y)**2 / len(y)
        if (loss < eps):
            break
        grad = tx.T @ (tx @ w -  y)/N
        w -= gamma * grad
    if (i == maxiters):
        print('Number of maxiterations reached.')    
    return (w,loss)

In [13]:
#Test for Gradient descent
np.random.seed(2)
dim = 4
test_X = 10*(np.random.rand(10,dim) -0.5)
wtrue = np.random.rand(dim)
print(test_X,'\n')
print('The real coeffs are ',wtrue,'\n')
test_y = test_X @ wtrue
w0 = np.random.rand(dim)
wfin = least_squares_GD(test_y,test_X,w0,100,0.03)
print('The found coeffs are ',wfin[0], ' and the error is ', wfin[1])


[[-0.64005098 -4.74073768  0.49662478 -0.64677607]
 [-0.79632198 -1.69665179 -2.95351366  1.19270966]
 [-2.00345326 -2.33172725  1.21133833  0.29142094]
 [-3.65420055  0.13578121 -3.15560134  2.85335148]
 [ 3.53975293 -0.05763163  3.46561485 -4.20354523]
 [ 0.0524609  -4.34713496 -0.71877672 -4.03469084]
 [-3.72840028  0.96745309 -2.73987999 -3.93054316]
 [-2.79693793 -1.50173715 -0.32212515 -2.98256774]
 [ 1.40406725 -0.16930164  0.0523672  -1.13107349]
 [ 2.93637454  0.80004179 -3.37701401  2.00752347]] 

The real coeffs are  [0.96455108 0.50000836 0.88952006 0.34161365] 

The found coeffs are  [0.966196   0.49574387 0.88923322 0.34396779]  and the error is  9.858645811462567e-05


In [14]:
print(wfin)

(array([0.966196  , 0.49574387, 0.88923322, 0.34396779]), 9.858645811462567e-05)


In [15]:
def least_square_SGD(y, tx, initial_w, max_iters, gamma):
    """
    Linear regression using SGD.
    Compute MSE loss
    """
    w = initial_w
    
    for i in range(max_iters):
        for y_batch, tx_batch in batch_iter(y, tx, batch_size=1, num_batches=1):
            # gradient
            gradient = compute_gradient_ls(y_batch, tx_batch, w)
           
            # update rule
            w -= gamma * gradient
            
            # loss
            loss = compute_loss_ls(y_batch, tx_batch, w)
            
    return w, loss

In [16]:
def least_squares(y, tx):
    """
    Least squares regression using normal equations.
    Note: better use solve. Problems occur when using np.linalg.inv()
    np.linalg.solve(a,b): solve problems of type ax=b
    """
    a = tx.T.dot(tx)
    b = tx.T.dot(y)
    
    w = np.linalg.solve(a, b)
    loss = compute_loss_ls(y, tx, w)
    
    return w, loss

In [17]:
def ridge_regression(y, tx, lambda_):
    """Ridge regression using normal equations."""
    N = tx.shape[0]
    D = tx.shape[1]
    a = tx.T.dot(tx) + 2*N*lambda_*np.identity(D)
    b = tx.T.dot(y)
    
    w = np.linalg.solve(a, b)
    loss = compute_loss_ls(y, tx, w)
        
    return w, loss

#### Logistic regression

In [18]:
def sigmoid(s):
    """apply sigmoid function."""
    return np.exp(s) / (1 + np.exp(s))

In [19]:
def compute_loss_lr(y, tx, w):
    """
    Compute the loss of the logistic regression
    by negative log likelihood.
    """
    prediction = sigmoid(tx.dot(w))
    loss = y.T.dot(np.log(prediction)) + (1 - y).T.dot(np.log(1 - prediction))
    return np.squeeze(-loss)

In [20]:
def compute_gradient_lr(y, tx, w):
    """compute the gradient of loss for the logistic regression."""
    prediction = sigmoid(tx.dot(w))
    gradient = tx.T.dot(prediction - y)
    return gradient

In [21]:
# GD version
def logistic_regression(y, tx, initial_w, max_iters, gamma):
    """Logistic regression using gradient descent or SGD."""
    # Note: we don't have to keep track of the weithts and losses
    w = initial_w
    
    # as we assume that the constant term is contained in x
    tx = np.c_[np.ones((y.shape[0], 1)), tx]
    
    # gradient descent
    for i in range(max_iters):
        # loss
        loss = compute_loss_lr(y, tx, w)

        # gradient
        gradient = compute_gradient_lr(y, tx, w)
        
        # update rule
        w -= gamma * gradient
    
    return w, loss

In [22]:
# SGD version
def logistic_regression(y, tx, initial_w, max_iters, gamma):
    """Logistic regression using gradient descent or SGD."""   
    w = initial_w
    
    # as we assume that the constant term is contained in x
    tx = np.c_[np.ones((y.shape[0], 1)), tx]
    
    # stochastic gradient descent
    for i in range(max_iters):
        for y_batch, tx_batch in batch_iter(y, tx, batch_size=1, num_batches=1): 
            # loss
            loss = compute_loss_lr(y_batch, tx_batch, w)

            # gradient
            gradient = compute_gradient_lr(y_batch, tx_batch, w)

            # update rule
            w -= gamma * gradient
    
    return w, loss

In [23]:
# GD version
def reg_logistic_regression(y, tx, lambda_, initial_w, max_iters, gamma):
    """Regularized logistic regression using gradient descent or SGD."""
    # same as before except that we have the additional penalty term
    w = initial_w
    
    # constant term contained in x
    tx = np.c_[np.ones((y.shape[0], 1)), tx]
    
    # gradient descent
    for i in range(max_iters):
        # loss
        loss =  compute_loss_lr + lambda_/2 *  np.squeeze(w.T.dot(w))
        
        # gradient
        gradient =  compute_gradient_lr + lambda_ * w
        
        # update rule
        w -= gamma * gradient
    
    return w, loss

In [24]:
# SGD version
def reg_logistic_regression(y, tx, lambda_, initial_w, max_iters, gamma):
    """Regularized logistic regression using gradient descent or SGD."""  
    w = initial_w
    
    # constant term contained in x
    tx = np.c_[np.ones((y.shape[0], 1)), tx]
    
    # gradient descent
    for i in range(max_iters):
        for y_batch, tx_batch in batch_iter(y, tx, batch_size=1, num_batches=1): 
            # loss
            loss = compute_loss_lr(y_batch, tx_batch, w) + lambda_/2 *  np.squeeze(w.T.dot(w))

            # gradient
            gradient = compute_gradient_lr(y_batch, x_batch, w) + lambda_ * w

            # update rule
            w -= gamma * gradient
    
    return w, loss

## Other useful methods

In [25]:
def train_test_split(X, y, ratio, seed=12):
    """Split the X and y sets into a training and a validation/testing one."""
    
    np.random.seed(seed)

    permutations = np.random.permutation(len(X))
    x = X[permutations]
    y = y[permutations]
    
    idx = int(np.floor(ratio * len(X)))
    x_train = x[:idx]
    y_train = y[:idx]
    x_test = x[idx:]
    y_test = y[idx:]
    
    return x_train, x_test, y_train, y_test

In [26]:
def accuracy(y, y_hat):
    """
    Compute the accuracy between the real values (y) 
    and the predicted ones (y_hat).
    Note: for binary predictions with values {0, 1} only.
    """
    return np.sum(y == y_hat) / len(y)

In [27]:
def k_fold_cv(y, X, k):
    """
    k-fold cross-validation for model selection.
    
    y: labels
    X: features matrix
    k: number of folds
    
    output: mean accuracy and std across the k-folds
    """
    
    # Before partitionning the data we shuffle it randomly
    permutations = np.random.permutation(len(y))
    X = X[permutations]
    y = y[permutations]
    
    # array to store the outcome accuracy  of the different folds
    accuracies = np.zeros(k)
    
    # Indexes for the k different intervals
    idxs = np.linspace(0, len(y), k+1, dtype=int) # +1 for 'upper bound'
     
    for i in range(nb_folds):
        X_te = X[idxs[i]:idxs[i+1]] #test indexes
        y_te = y[idxs[i]:idxs[i+1]]
        
        X_tr = np.delete(X, list(np.arange(idxs[i], idxs[i+1])), axis=0)
        y_tr = np.delete(y, list(np.arange(idxs[i], idxs[i+1])), axis=0)
        
        ## TODO: implement the classifier part 
        # 1. fit data
        # 2. compute y_hat
        # 3. compute accuracy
    
    return np.mean(accuracies), np.std(accuracies)

## Do your thing crazy machine learning thing here :) ... Mais jpeeeeense alors!

## Generate predictions and save ouput in csv format for submission:

In [ ]:
DATA_TEST_PATH = '../data/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [ ]:
OUTPUT_PATH = '' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

In [ ]:
#Template for plotting graph in 3D later.
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.gca(projection='3d')
x = np.linspace(-1,1,10)
y = np.linspace(-1,1,10)
xp,yp = np.meshgrid(x,y)
z = xp**2 + yp**2
surf = ax.plot_surface(xp,yp,z)
k = np.rand()